=== crux-toolkit/crux-toolkit/src/external/xsd/tests/cxx/tree/binary/cdr/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:t="test"
        targetNamespace="test">

  <simpleType name="list">
    <list itemType="int"/>
  </simpleType>

  <simpleType name="union">
    <union memberTypes="int string"/>
  </simpleType>

  <simpleType name="enumeration">
    <restriction base="string">
      <enumeration value="top"/>
      <enumeration value="left"/>
      <enumeration value="bottom"/>
      <enumeration value="right"/>
    </restriction>
  </simpleType>

  <complexType name="base">
    <sequence>
      <element name="a" type="string"/>
    </sequence>
    <attribute name="x" type="int" use="required"/>
  </complexType>

  <complexType name="complex">
    <complexContent>
      <extension base="t:base">
        <sequence>
          <element name="b" type="string" minOccurs="0"/>
	  <element name="c" type="string" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
	<attribute name="y" type="int"/>
      </extension>
    </complexContent>
  </complexType>


  <complexType name="type">
    <sequence>
      <element name="list" type="t:list"/>
      <element name="union" type="t:union"/>
      <element name="enumeration" type="t:enumeration"/>
      <element name="complex" type="t:complex" maxOccurs="unbounded"/>

      <!-- integers -->
      <element name="byte"                  type="byte"/>
      <element name="unsigned_byte"         type="unsignedByte"/>
      <element name="short"                 type="short"/>
      <element name="unsigned_short"        type="unsignedShort"/>
      <element name="int"                   type="int"/>
      <element name="unsigned_int"          type="unsignedInt"/>
      <element name="long"                  type="long"/>
      <element name="unsigned_long"         type="unsignedLong"/>
      <element name="integer"               type="integer"/>
      <element name="non_positive_integer"  type="nonPositiveInteger"/>
      <element name="non_negative_integer"  type="nonNegativeInteger"/>
      <element name="positive_integer"      type="positiveInteger"/>
      <element name="negative_integer"      type="negativeInteger"/>


      <!-- boolean -->
      <element name="boolean"               type="boolean"/>


      <!-- floats -->
      <element name="float"                 type="float"/>
      <element name="double"                type="double"/>
      <element name="decimal"               type="decimal"/>


      <!-- strings -->
      <element name="string"                type="string"/>
      <element name="normalized_string"     type="normalizedString"/>
      <element name="token"                 type="token"/>
      <element name="name"                  type="Name"/>
      <element name="name_token"            type="NMTOKEN"/>
      <element name="name_tokens"           type="NMTOKENS"/>
      <element name="ncname"                type="NCName"/>
      <element name="language"              type="language"/>

      <!-- qualified name -->
      <element name="qname"                 type="QName"/>


      <!-- ID/IDREF -->
      <element name="id"     maxOccurs="2"  type="ID"/>
      <element name="id_ref"                type="IDREF"/>
      <element name="id_refs"               type="IDREFS"/>


      <!-- URI -->
      <element name="any_uri"               type="anyURI"/>


      <!-- binary -->
      <element name="base64_binary"         type="base64Binary"/>
      <element name="hex_binary"            type="hexBinary"/>


      <!-- date/time -->
      <element name="date"                  type="date"/>
      <element name="date_time"             type="dateTime"/>
      <element name="duration"              type="duration"/>
      <element name="day"                   type="gDay"/>
      <element name="month"                 type="gMonth"/>
      <element name="month_day"             type="gMonthDay"/>
      <element name="year"                  type="gYear"/>
      <element name="year_month"            type="gYearMonth"/>
      <element name="time"                  type="time"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== crux-toolkit/crux-toolkit/src/external/xsd/tests/cxx/tree/binary/xdr/test.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <list>1 2 3</list>

  <union>abc</union>

  <enumeration>left</enumeration>

  <complex x="1">
    <a>aaa</a>
  </complex>
  <complex x="1" y="2">
    <a>aaa</a>
    <b>bbb</b>
    <c>c</c>
    <c>cc</c>
    <c>ccc</c>
  </complex>


  <!-- integers -->
  <byte>65</byte>
  <unsigned_byte>66</unsigned_byte>
  <short>-222</short>
  <unsigned_short>57005</unsigned_short>
  <int>-57005</int>
  <unsigned_int>3735928559</unsigned_int>
  <long>-3735928559</long>
  <unsigned_long>16045690984833335023</unsigned_long>
  <integer>-3735928559</integer>
  <non_positive_integer>-3735928559</non_positive_integer>
  <non_negative_integer>3735928559</non_negative_integer>
  <positive_integer>3735928559</positive_integer>
  <negative_integer>-3735928559</negative_integer>


  <!-- boolean -->
  <boolean>true</boolean>


  <!-- floats -->
  <float>1234.1234</float>
  <double>12345678.12345678</double>
  <decimal>1234567812345678.1234567812345678</decimal>


  <!-- strings -->
  <string>string</string>
  <normalized_string>normalized string</normalized_string>
  <token>one two three</token>
  <name>name</name>
  <name_token>name-token</name_token>
  <name_tokens>name tokens</name_tokens>
  <ncname>ncname</ncname>
  <language>en-us</language>

  <!-- qualified name -->
  <qname>xsi:schemaLocation</qname>


  <!-- ID/IDREF -->
  <id>elements1</id>
  <id>elements2</id>
  <id_ref>elements1</id_ref>
  <id_refs>elements1 elements2</id_refs>


  <!-- URI -->
  <any_uri>http://www.codesynthesis.com</any_uri>


  <!-- binary -->
  <base64_binary>YmFzZTY0IGJpbmFyeQ==</base64_binary>
  <hex_binary>6865782052696E617279</hex_binary>


  <!-- date/time -->
  <date>2001-10-26+02:00</date>
  <date_time>2001-10-26T21:32:52+02:00</date_time>
  <duration>P1Y2M3DT5H20M30S</duration>
  <day>---01+02:00</day>
  <month>--11+02:00</month>
  <month_day>--11-02+02:00</month_day>
  <year>2001+02:00</year>
  <year_month>2001-11+02:00</year_month>
  <time>21:32:52+02:00</time>


</t:root>
