=== crux-toolkit/crux-toolkit/src/external/xsd/examples/cxx/tree/custom/mixed/people.xsd
<?xml version="1.0"?>

<!--

file      : examples/cxx/tree/custom/mixed/people.xsd
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : not copyrighted - public domain

-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:ppl="http://www.codesynthesis.com/people"
            targetNamespace="http://www.codesynthesis.com/people">

  <xsd:simpleType name="gender">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="male"/>
      <xsd:enumeration value="female"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="bio" mixed="true">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:any namespace="http://www.w3.org/1999/xhtml" processContents="skip"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="person">
    <xsd:sequence>
      <xsd:element name="first-name" type="xsd:string"/>
      <xsd:element name="last-name" type="xsd:string"/>
      <xsd:element name="gender" type="ppl:gender"/>
      <xsd:element name="age" type="xsd:unsignedShort"/>
      <xsd:element name="bio" type="ppl:bio"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="directory">
    <xsd:sequence>
      <xsd:element name="person" type="ppl:person" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="directory" type="ppl:directory"/>

</xsd:schema>

=== crux-toolkit/crux-toolkit/src/external/xsd/examples/cxx/tree/xpath/people.xml
<?xml version="1.0"?>

<!--

file      : examples/cxx/tree/xpath/people.xml
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : not copyrighted - public domain

-->

<ppl:directory xmlns:ppl="http://www.codesynthesis.com/people"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.codesynthesis.com/people people.xsd">

  <person>
    <first-name>John</first-name>
    <last-name>Doe</last-name>
    <gender>male</gender>
    <age>32</age>
  </person>

  <person>
    <first-name>Jane</first-name>
    <last-name>Doe</last-name>
    <gender>female</gender>
    <age>28</age>
  </person>

</ppl:directory>
