=== crux-toolkit/crux-toolkit/src/external/xsd/examples/cxx/tree/streaming/position.xsd
<?xml version="1.0"?>

<!--

file      : examples/cxx/tree/streaming/position.xsd
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : not copyrighted - public domain

-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	    xmlns:op="http://www.codesynthesis.com/op"
            targetNamespace="http://www.codesynthesis.com/op">


  <xsd:complexType name="header">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="type" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="position">
    <xsd:attribute name="lat" type="xsd:float" use="required"/>
    <xsd:attribute name="lon" type="xsd:float" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="object">
    <xsd:sequence>
      <xsd:element name="header" type="op:header"/>
      <xsd:element name="position" type="op:position" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:unsignedInt" use="required"/>
  </xsd:complexType>

  <xsd:element name="object" type="op:object"/>

</xsd:schema>

=== crux-toolkit/crux-toolkit/src/external/xsd/examples/cxx/tree/streaming/position.xml
<?xml version="1.0"?>

<!--

file      : examples/cxx/tree/streaming/position.xml
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : not copyrighted - public domain

-->

<op:object xmlns:op="http://www.codesynthesis.com/op"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:schemaLocation="http://www.codesynthesis.com/op position.xsd"
           id="123">

  <header>
    <name>Lion's Head</name>
    <type>rock</type>
  </header>

  <position lat="-33.8569" lon="18.5083"/>
  <position lat="-33.8568" lon="18.5083"/>
  <position lat="-33.8568" lon="18.5082"/>
  <position lat="-33.8570" lon="18.5083"/>
  <position lat="-33.8569" lon="18.5084"/>
  <position lat="-33.8570" lon="18.5084"/>
  <position lat="-33.8570" lon="18.5082"/>
  <position lat="-33.8569" lon="18.5082"/>

</op:object>
